fieldplayers_attributes = {
        'age':    ('Unnamed: 5_level_0', 'Age'),
        'born':    ('Unnamed: 6_level_0', 'Born'),
        'match_played':    ('Playing Time_x', 'MP'),
        'starts'    :('Playing Time_x', 'Starts'),
        'min_played':    ('Playing Time_x', 'Min'),
        '90s':    ('Playing Time_x', '90s'),
        'Goals'   : ('Performance_x', 'Gls'),
        'Assists' :    ('Performance_x', 'Ast'),
        'Goals without Penalty Kicks':    ('Performance_x', 'G-PK'),
        'Gaols Penalty Kick' :    ('Performance_x', 'PK'),
        'Penalty Kicks attempted':    ('Performance_x', 'PKatt'),
        'Yellow cards':    ('Performance_x', 'CrdY'),
        'Red cards':    ('Performance_x', 'CrdR'),
        'Goals per 90min':    ('Per 90 Minutes', 'Gls'),
        'Assists per 90min':    ('Per 90 Minutes', 'Ast'),
        'Goals + Assists per 90min':    ('Per 90 Minutes', 'G+A'),
        'Goals without Penalty kicks per 90min':    ('Per 90 Minutes', 'G-PK'),
        'Goals + Assists without Penalty kicks per 90min' : ('Per 90 Minutes', 'G+A-PK'),
        'xG':   ('Expected_x', 'xG'),
        'npxG':    ('Expected_x', 'npxG'),
        'xA':    ('Expected_x', 'xA'),
        'npxG+xA':    ('Expected_x', 'npxG+xA'),
        'xG per 90min':    ('Per 90 Minutes', 'xG'),
        'xA per 90min':    ('Per 90 Minutes', 'xA'),
        'xG + xA per 90min':    ('Per 90 Minutes', 'xG+xA'),
        'npxG per 90min':    ('Per 90 Minutes', 'npxG'),
        'npxG+xA per 90min':    ('Per 90 Minutes', 'npxG+xA'),
        'Shots':    ('Standard', 'Sh'),
        'Shots on target' :    ('Standard', 'SoT'),
        'Shots on target%' :    ('Standard', 'SoT%'),
        'Shots per 90min'  :    ('Standard', 'Sh/90'),
        'Shots on target per 90min'  : ('Standard', 'SoT/90'),
        'Goals per shot' :    ('Standard', 'G/Sh'),
        'Goals per Shot on target' :    ('Standard', 'G/SoT'),
        'Avg shot distance (yards)':     ('Standard', 'Dist'),
        'Shots from free kick':    ('Standard', 'FK'),
        'Penalty kicks made':    ('Performance_y', 'PK'),
        'Penalty kicks attempted':    ('Performance_y', 'PKatt'),
        'npxG/shot' : ('Expected_y', 'npxG/Sh'),
        'goals - xG':    ('Expected_y', 'G-xG'),
        'non-penalty goals - non-penalty xG': ('Expected_y', 'np:G-xG'),
        'Passes completed (total)':    ('Total', 'Cmp'),
        'Passes attempted (total)':    ('Total', 'Att'),
        'Passes completed %':    ('Total', 'Cmp%'),
        'Passes total distance':    ('Total', 'TotDist'),
        'Passes proggressive distance':    ('Total', 'PrgDist'),
        'Passes completed (short)' :    ('Short', 'Cmp'),
        'Passes attempted (short)' :    ('Short', 'Att'),
        'Passes completed % (short)' :    ('Short', 'Cmp%'),
        'Passes completed (medium)':    ('Medium', 'Cmp'),
        'Passes attempted (medium)':    ('Medium', 'Att'),
        'Passes completed % (medium)':    ('Medium', 'Cmp%'),
        'Passes completed (long)':    ('Long', 'Cmp'),
        'Passes attempted (long)':    ('Long', 'Att'),
        'Passes completed % (long)':    ('Long', 'Cmp%'),
        'Assists - xA': ('Unnamed: 24_level_0', 'A-xA'),
        'Key Passes' :    ('Unnamed: 25_level_0', 'KP'),
        'Passes to final 3rd':    ('Unnamed: 26_level_0', '1/3'),
        'Passes to penalt area':    ('Unnamed: 27_level_0', 'PPA'),
        'Crosses to penalty area':    ('Unnamed: 28_level_0', 'CrsPA'),
        'Progressive passes':    ('Unnamed: 29_level_0', 'Prog'),
        'Passes - live-ball':  ('Pass Types', 'Live'),
        'Passes - dead-ball':    ('Pass Types', 'Dead'),
        'Passes free kick':    ('Pass Types', 'FK'),
        'Passes - trough balls' :    ('Pass Types', 'TB'),
        'Passes under pressure':    ('Pass Types', 'Press'),
        'Pass type switch (40 yars width)':   ('Pass Types', 'Sw'),
        'Pass type cross':    ('Pass Types', 'Crs'),
        'Corner kicks':    ('Pass Types', 'CK'),
        'Touches':  ('Touches', 'Touches'),
        'Touches defensive penalty area' :    ('Touches', 'Def Pen'),
        'Touches defensive 3rd' :('Touches', 'Def 3rd'),
        'Touches midfield 3rd' :('Touches', 'Mid 3rd'),
        'Touches attacking 3rd':    ('Touches', 'Att 3rd'),
        'Touches attacking penalty area':    ('Touches', 'Att Pen'),
        'Dribbles successful' : ('Dribbles', 'Succ'),
        'Dribbles attempted' :    ('Dribbles', 'Att'),
        'Dribbles successful %' :('Dribbles', 'Succ%'),
        'Dribbles #players dribbled past' :    ('Dribbles', '#Pl'),
        'Dribbles nutmegs' :    ('Dribbles', 'Megs'),
        'Carries':    ('Carries', 'Carries'),
        'Carries total distance':    ('Carries', 'TotDist'),
        'Carries progressive distance' :    ('Carries', 'PrgDist'),
        'Carries progressive':    ('Carries', 'Prog'),
        'Carries to 1/3':    ('Carries', '1/3'),
        'Carries to Penalty area':    ('Carries', 'CPA'),
        'Receiving - targetted passes' : ('Receiving', 'Targ'),
        'Receiving - received passes' :   ('Receiving', 'Rec'),
        'Receiving - received %' :    ('Receiving', 'Rec%'),
        'Receiving - progressive passes received' :    ('Receiving', 'Prog'),
        'Tackles':    ('Tackles', 'Tkl'),
        'Tackles won' : ('Tackles', 'TklW'),
        'Tackles defensive 3rd':    ('Tackles', 'Def 3rd'),
        'Tackles midfield 3rd' :    ('Tackles', 'Mid 3rd'),
        'Tackles attacking 3rd' :   ('Tackles', 'Att 3rd'),
        'Dribbled past' :    ('Vs Dribbles', 'Past'),
        'Pressures':    ('Pressures', 'Press'),
        'Pressures successful':    ('Pressures', 'Succ'),
        'Pressures successful %' :    ('Pressures', '%'),
        'Pressures def 3rd':    ('Pressures', 'Def 3rd'),
        'Pressures mid 3rd':    ('Pressures', 'Mid 3rd'),
        'Pressures att 3rd' : ('Pressures', 'Att 3rd'),

        'Interceptions':    ('Unnamed: 27_level_0', 'Int'),
        'Clearences' :('Unnamed: 29_level_0', 'Clr'),
        'Errors leading to shot':    ('Unnamed: 30_level_0', 'Err'),
        'Matches played':    ('Playing Time_y', 'MP'),
        'Minutes played':    ('Playing Time_y', 'Min'),
        'Minutes per match':    ('Playing Time_y', 'Mn/MP'),
        'Minutes %':    ('Playing Time_y', 'Min%'),
        'Starts':    ('Playing Time_y', 'Starts')

        }